name: GGG-Anarchy
main: ml.gggrealms.gggmcanarchy.AnarchyPlugin
version: 0.0.1
description: "Anarchy plugin base for GGG Anarchy Server"
api-version: 1.19
author: "GGGDunlix"
commands:
  gggmcanarchy:
    aliases: gggmca
    usage: "/gggmcanarchy"
  savequit:
    description: "Saves your progress and leaves the server"
    aliases: quit
    usage: "/savequit"
  class:
    description: "allows you to spawn as a class. Only unlocked classes can be used. Certain properties need to be owned in order to unlock classes."
    usage: "/class <class>"
  editconfig:
    description: "edits the server config file"
    usage: "/editconfig <String path> <Object value>"
    permission: op
    permission-message: "You lack sufficient permissions for such a command execution, dude."
  enter:
    aliases: ["exit"]
    description: "Allows you to enter/exit spaces while standing on that prompt's respective stone blocks. Usually, a sign will be where you are supposed to use this command."
    usage: "/enter"

