name: GGG-Anarchy
main: ml.gggrealms.gggmcanarchy.AnarchyPlugin
version: 0.0.1
description: "Anarchy plugin base for GGG Anarchy Server"
api-version: 1.19
author: "GGGDunlix"
commands:
  gggmcanarchy:
    aliases: gggmca
    usage: "/gggmcanarchy"
  savequit:
    description: "Saves your progress and leaves the server"
    aliases: quit
    usage: "/savequit"
  class:
    aliases: ["c"]
    description: "allows you to spawn as a class. Only unlocked classes can be used. Certain properties need to be owned in order to unlock classes."
    usage: "/class <class>"
  editconfig:
    description: "edits the server config file"
    usage: "/editconfig <String path> <Object value>"
    permission: op
    permission-message: "You lack sufficient permissions for such a command execution, dude."
  enter:
    aliases: ["exit", "e"]
    description: "Allows you to enter/exit spaces while standing on that prompt's respective stone blocks. Usually, a sign will be where you are supposed to use this command."
    usage: "/e"
  money:
    aliases: ["m"]
    description: "shows you how much cash you have on your person. You lose this when you die."
    usage: "/money"
  retire:
    description: "Retires from your class/faction and respawns you, while allowing you to keep your items and money."
    usage: "/retire"
  autospawn:
    description: "Changes whether or not you automatically spawn as default class, and the rate at which this occurs."
    aliases:
      - "as"
      - "autoclass"
    usage: "/autospawn <true|false|int seconds>"
  givemoney:
    permission: op
  safe:
    description: "Allows safe/money management"
  join:
    description: "Allows you to join factions. Can only use while in that faction's homebase."
    aliases:
      - "j"
  sell:
    description: "sells things at specific spots from your inventory. Stand on the smooth stone."
  buy:
    description: "buys things at specific spots for money. Stand on the smooth stone."
  bugreport:
    description: "Useful for reporting bugs, errors, problems, or glitches to the devs."
    aliases:
      - "bug"
      - "br"
      - "breport"
  properties:
    description: "Shows info about properties around the world"
  stash:
    description: "Opens the weapons/items stash inside properties."
  editcfg:
    permission: op

